### ISSUE TITLE
Fix production deployment

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#135]
@ubergesundheit could you take a look at: https://github.com/codeformuenster/muenster-jetzt/actions/runs/227165806

looks like  the "check for changes" does prevent a docker hub tag

i've created a new branch for this: https://github.com/codeformuenster/muenster-jetzt/tree/fix-production-build where i will fix the docker-compose file (which is missing the correct tags for production)

**Comment by ubergesundheit** [comment]
44252d9 maybe fixes this

**Comment by bCyberBasti** [comment]
@ubergesundheit "maybe" was the right wording 😸 

see https://github.com/codeformuenster/muenster-jetzt/actions/runs/227405981
