### ISSUE TITLE
Redirect old url(s)

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#158]
Please configure  a redirect for all the old urls to https://muenster-jetzt.de

**Comment by tomsrocket** [comment]
Moinsen! What für all the old urls are you talking about? :) Meinst du die ganzen *.muenster.jetzt subdomains? die hab ich mal alle mit ".old" geprefixt, und außerdem * auf die neue ip eingerichtet. Passt das so?

**Comment by bCyberBasti** [comment]
Passt, danke 😄

**Comment by bCyberBasti** [comment]
ToDo for myself: configure traefik for the redirect of `muenster.jetzt`

**Comment by bCyberBasti** [comment]
closed by #166
