### ISSUE TITLE
(DOK-DL3018) Pin versions in `apk add`

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#159]
## Description
Version pinning forces the build to retrieve a limited range of versions, or an exact particular version, regardless of what’s in the cache. This technique can also reduce failures due to unanticipated changes in required packages. &gt; https://docs.docker.com/engine/articles/dockerfile_best-practices/ Problematic code: ```dockerfile FROM alpine:3.7 RUN apk --no-cache add foo ``` Correct …

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/codeformuenster/muenster-jetzt/issue/DOK-DL3018/occurrences/](https://deepsource.io/gh/codeformuenster/muenster-jetzt/issue/DOK-DL3018/occurrences/)

**Comment by ubergesundheit** [comment]
Resolved in https://github.com/codeformuenster/muenster-jetzt/pull/181
