### ISSUE TITLE
(PYL-W0621) Re-defined variable from outer scope

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#160]
## Description
Local variable name hides the variable defined in the outer space, making it inaccesible. It may cause confusion.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-W0621/occurrences/](https://deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-W0621/occurrences/)

**Comment by ebleb** [comment]
I believe this issue could be closed, as it was resolved by the new backend(#268).

**Comment by ubergesundheit** [comment]
Seems right :)
