### ISSUE TITLE
(PYL-W0613) Function contains unused argument

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#161]
## Description
An unused argument can lead to confusions. It should be removed. If this variable is necessary, name the variable `_` or start the name with `unused` or `_unused`.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-W0613/occurrences/](https://deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-W0613/occurrences/)

**Comment by ubergesundheit** [comment]
Ignoring this until we notice performance issues: See https://github.com/codeformuenster/muenster-jetzt/pull/316#issuecomment-753467899
