### ISSUE TITLE
(PYL-W1508) Invalid `envvar` default

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#162]
## Description
Env manipulation functions return `None` or `str` values. Supplying anything different as a default may cause bugs. See https://docs.python.org/3/library/os.html#os.getenv.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-W1508/occurrences/](https://deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-W1508/occurrences/)

**Comment by ubergesundheit** [comment]
Ignoring this until we notice performance issues: See https://github.com/codeformuenster/muenster-jetzt/pull/316#issuecomment-753467899
