### ISSUE TITLE
(PYL-R0201) No use of `self`

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#163]
## Description
The method doesn&#x27;t use its bound instance. Decorate this method with `@staticmethod` decorator, so that Python does not have to instantiate a bound method for every instance of this class thereby saving memory and computation. Read more about staticmethods [here](https://docs.python.org/3/library/functions.html#staticmethod).

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-R0201/occurrences/](https://deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-R0201/occurrences/)

Feel free to try the magic "AUTOFIX Button" found over here https://deepsource.io/gh/codeformuenster/muenster-jetzt/issue/PYL-R0201/occurrences 😉

**Comment by ubergesundheit** [comment]
Ignoring this until we notice performance issues: See https://github.com/codeformuenster/muenster-jetzt/pull/316#issuecomment-753467899
