### ISSUE TITLE
video content?

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#177]

**Comment by ubergesundheit** [comment]
Can you share the video url?

**Comment by bCyberBasti** [comment]
Will sent you the url in private (think its a non public preview version) 😉

**Comment by ubergesundheit** [comment]
Video autoplay without prior user interaction needs setting chromium flag `chrome://flags/#autoplay-policy` to `No user gesture is required`  ([Source](https://stackoverflow.com/a/50222347))

**Comment by bCyberBasti** [comment]
Did you test it? It reads like autoplaying with sound is the problem? For our use case it would be perfectly fine to mute the video as we don't have any speakers..

**Comment by ubergesundheit** [comment]
Yes, I faced this problem during development which led me to look this up.

**Comment by ubergesundheit** [comment]
A (really silly) workaround could be to render the video into an canvas, but I this seems like an overkill IMO

**Comment by ubergesundheit** [comment]
Tried this now again with `muted` and `autoplay`. Seems to work.

**Comment by ubergesundheit** [comment]
@bCyberBasti please close this once confirmed working (#197)

**Comment by bCyberBasti** [comment]
worked like a charm 🎉 🎥
