### ISSUE TITLE
QR scannable?

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/muenster-jetzt#182]
My Iphone SE cannot scan any QR codes live on muenster-jetzt.de (may be related to 14 inch laptop display)

**Comment by bCyberBasti** [comment]
Yes small screen sizes are a problem.. in real live the smallest display (so far) was 49" but i will keep it in the back of my head for the next test and will try to check with a "cheap phone" if QR Code Size is a problem

**Comment by ubergesundheit** [comment]
@bCyberBasti added some stuff in #223 which should resolve this. Reopen if this still happens
