### ISSUE TITLE
Invalid event url

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/muenster-jetzt#207]
Opening this issue for awareness.

Event "Demoday #9 Digital Hub Accelerator" has an invalid url. I did not verify the event at the source but I think the invalid value is coming directly from there.

For now, I won't display the url if its's not starting with http:// or https://

<details>

<summary>JSON</summary>

```
{
  "id": 36,
  "source": {
    "id": 1,
    "name": "münsterLAND.digital"
  },
  "sourceEventId": "1058",
  "sourceUrl": null,
  "sourceLicense": "CC BY-SA 4.0",
  "name": "Demoday #9 Digital Hub Accelerator",
  "description": "Beim Demoday sprechen die Startups aus dem Digital Hub Accelerator über ihre Suche nach Kooperationspartnern aus dem Mittelstand, ersten Kunden und Investoren. Zum anderen laden wir weitere Startups aus dem DWNRW-Hub Netzwerk zum Demoday ein.",
  "url": "demoday-digitalhub-accelerator",
  "startDate": "2020-09-17",
  "startTime": "17:00:00",
  "endDate": null,
  "endTime": null,
  "location": {
    "id": 17,
    "description": "Livestream"
  },
  "performer": null,
  "mode": "Pitch",
  "organizer": {
    "id": 4,
    "name": "Digital Hub münsterLAND"
  },
  "images": []
}
```

</details>

**Comment by ubergesundheit** [comment]
@jdemaeyer can you take a look? Is this an issue with the upstream source or is there something wrong in the scraper?

**Comment by jdemaeyer** [comment]
I can't check with the source unfortunately as their API doesn't return events from the past, but I doubt it's an issue with the crawler as we simply copy their `link_url` field verbatim
