### ISSUE TITLE
@u-rogel you can already take a look at this PR. Ideally you would provide your changes in a new branch and new PR into this branch.

### ISSUE THREAD

**Issue by u-rogel** [codeformuenster/muenster-jetzt#208]
@u-rogel you can already take a look at this PR. Ideally you would provide your changes in a new branch and new PR into this branch.

_Originally posted by @ubergesundheit in https://github.com/codeformuenster/muenster-jetzt/pull/204#issuecomment-693526271_

So I will start building UI components to it later on. We take the design from Figma yes?

**Comment by ubergesundheit** [comment]
Just go wild, we can iterate user feedback later on

**Comment by u-rogel** [comment]
@ubergesundheit  I guess I will need help with the types on some spots :disappointed: 
I have no idea what I should give it on [this line](https://github.com/codeformuenster/muenster-jetzt/blob/a03ab62a11d34a3dc6fc49fa724f791587a81551/frontend/src/UI/Layout/Layout.tsx#L15) (`./frontend/src/UI/Layout/Layout.tsx(15,26)`) to avoid this error - 
`Property 'date' does not exist on type '{}'.  TS2339`

**Comment by ubergesundheit** [comment]
Check out [App.tsx](https://github.com/codeformuenster/muenster-jetzt/blob/a03ab62a11d34a3dc6fc49fa724f791587a81551/frontend/src/App/App.tsx#L17). The `date`parameter is already handled there. IMOs this file is also the place your code should live.

**Comment by ubergesundheit** [comment]
I'll close this, we can use other issues
