### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#220]
![image](https://user-images.githubusercontent.com/66736282/93749242-e07df100-fbf9-11ea-8e5b-cb7b7276ff83.png)

**Comment by bCyberBasti** [comment]
In Brave (Chrome based) and Safari so i guess its macOS related

**Comment by ubergesundheit** [comment]
Can you confirm this is also happening on https://fonts.google.com/specimen/Recursive?selection.family=Recursive#standard-styles ?

**Comment by bCyberBasti** [comment]
> Can you confirm this is also happening on https://fonts.google.com/specimen/Recursive?selection.family=Recursive#standard-styles ?

Nop, there everything looks fine

**Comment by simsal0r** [comment]
![grafik](https://user-images.githubusercontent.com/35310222/94588914-e53f4680-0284-11eb-9152-416a226ff4c9.png)
Windows 10, Firefox

**Comment by ubergesundheit** [comment]
Finally resolved in #256
