### ISSUE TITLE
sanitize html in our api

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#227]
idea: lets store raw data from the source and populate other fields in a safe way but keep the raw data accessible for api consumers

@jdemaeyer and @ThorbenJensen what is your opinion on this?

**Comment by ThorbenJensen** [comment]
i like the idea of storing the raw data in a first stage.
that change might require (but also bring the opportunity of) rewriting the data ingestion.

@bCyberBasti 
what usecases do you see for pulling the HTML directly?

**Comment by bCyberBasti** [comment]
> what usecases do you see for pulling the HTML directly?

Sorry for the missing context.. the idea is based on the fact that the new datenportal api is returning html as a string for e.g. the description of events

**Comment by jdemaeyer** [comment]
So there's two independent ideas/requirements discussed here, right?

1. We need to sanitize Münsterland e.V. event descriptions, and
2. We possibly want to store raw API data

@bCyberBasti when you say "raw data", do you mean "raw description including HTML" or do you mean "the complete API response [for this event]", it's not clear to me from the issue title vs. description :sweat_smile:

I see very few use cases for the former one. The latter one could be useful in re-parsing already-crawled events if we add new fields, but that seems overkill compared to just re-crawling the source given that our crawls consist of exactly one HTTP request. ;)

Removing HTML tags looks like a high-priority business requirement to me. I've had good experiences using [Bleach](https://github.com/mozilla/bleach) to do this, I'll open a PR later today. As I said above I don't see any big gain in storing raw data, it seems like a misallocation of our quite limited resources to me. That being said I will of course still happily review a PR if someone wants me to :)
