### ISSUE TITLE
Improve Infrastructure CI

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#65]
From another discussion

> Running the playbook by automation would have the benefit of forcing us to really to keep the configuration in the repository in line with the server in the sense that manual changes would be overwritten. That would require discipline.
> 
> Maybe we could do a middle ground:
> 
> Build the image in ci and push it to the docker hub and then basically copy the front end deployment.

**Comment by ubergesundheit** [comment]
We know how to set up a server. This is out of scope for now
