### ISSUE TITLE
Add deepsource?

### ISSUE THREAD

**Issue by bCyberBasti** [codeformuenster/muenster-jetzt#71]
Just stumbled up on https://deepsource.io/ it looks like they are free for open source projects and would love to try it out 😄
Looking for feedback, especially from  @ubergesundheit @jdemaeyer  😉

**Comment by ubergesundheit** [comment]
Repository is public now.

**Comment by bCyberBasti** [comment]
Tried the installation.. but it looks like I don't have the permissions to allow the integration?
![image](https://user-images.githubusercontent.com/66736282/91544250-c06f5080-e91f-11ea-8eed-729ccfefbaae.png)

@ubergesundheit are you an admin of codeformuenster and could check if there is some kind of notification to allow that integration?

**Comment by ubergesundheit** [comment]
I've activated it and also its autofix feature https://deepsource.io/gh/codeformuenster/muenster-jetzt/
